### ISSUE TITLE
Could we add more code samples in manpages?

### ISSUE THREAD

**Issue by dthree** [wooorm/mdast#44]
https://github.com/wooorm/mdast/blob/master/doc/mdastplugin.3.md

In this page, I am trying very hard to understand how to create and manipulate plugins. While I know concepts have been organized in a very able way, you are introducing a log of new terms as `attacher`, `transformer` and `completer`. 

There is but one code example on creating a plugin, and this only implements the `transformer`. Code samples are are to coders as pictures are to anyone else in a manual. They put things in perspective. I am having a very hard time figuring out how to implement these definitions above, and if more snippits were given, I am sure this could be simplified greatly. 

Example:

> To access all files once they are transformed, create a completer. A completer is invoked before files are compiled, written, and logged, but after reading, parsing, and transforming. Thus, a completer can still change files or add messages.

Where does one create a signature? A simple example would be worth another 5 paragraphs of description.

**Comment by wooorm** [comment]
Sorry about that! I really try to add as much docs as possible, but it’s hard to keep everything up to date, and to document everything as well as possible (especially because I currently do all the work 😉)

Also, you really picked the most difficult, hidden gem there is (the `completer`). I added those to test initial integration with mdast(1) by plug-ins. It’s currently in use only by [**mdast-validate-links**](https://github.com/wooorm/mdast-validate-links). There, it follows links (either to github blobs or local), and adds them to be processed by mdast. Then, when all files are processed, it checks all deep anchor links to unknown headings.

I agree that there should be more examples though. I’ll try to work on them soon. Until then, I can only suggest to read the source code of other mdast plugins!

**Comment by dthree** [comment]
Thanks and got it.

BTW, I do want you to know that I'm actually impressed with how thorough and well arranged your code and docs are. Your docs read that you put a lot of time and care into them, so I think code snippits just completes that effort and makes it fully worthwhile :)

I am starting to get the hang of it all, and as I mature in my understanding of `MDAST`, I can absolutely contribute to the docs. Right now if I tried to contribute, I think I would just botch the more complicated parts, haha!
