### ISSUE TITLE
Add an option to output something when no messages are found

### ISSUE THREAD

**Issue by chcokr** [wooorm/mdast#59]
Spin off from #57

**Comment by chcokr** [comment]
@wooorm I can tackle this within the next week or so. What do you want the option to be called? Also, any hints?

**Comment by wooorm** [comment]
Thanks for the interest, @chcokr. I just started working on this
but it doesn’t seem very useful anymore since e3748d2.
That commit ensured only a single file, even when a huge amount of documents
are watched, is processed. Thus, instead of seeing a long list of document, a single file is shown now:

```sh
$ mdast -w .
# Watching... (press CTRL+C to exit)
# 
# doc/getting-started.md: no issues found
# ...
# test/cli/markdown.md: no issues found
# Warning: mdast does not overwrite watched files until exit.
# Messages and other files are not affected.
# ⠴
# {{change readme.}}
# readme.md: no issues found
# ⠼
```

This, if you’d like, can be suppressed with `-q`, `--quiet`:

```sh
$ mdast -qw .
# Watching... (press CTRL+C to exit)
# Warning: mdast does not overwrite watched files until exit.
# Messages and other files are not affected.
# ⠴
# {{change readme.}}
# ⠼
```

Thus, I think that this is already fixed by our recent work!

**Comment by chcokr** [comment]
Gotcha. Cool!

**Comment by wooorm** [comment]
:+1:
