### ISSUE TITLE
mdast wants links to images surrounded by <>

### ISSUE THREAD

**Issue by sils1297** [wooorm/mdast#93]
That change gets proposed when I regenerate my markdown file:

```diff
-[![Scrutinizer Code Quality](https://img.shields.io/scrutinizer/g/coala-analyzer/coala.svg?label=scrutinizer quality)](https://scrutinizer-ci.com/g/coala-analyzer/coala/?branch=master) [![codecov.io](https://img.shields.io/codecov/c/github/coala-analyzer/coala/master.svg?label=branch coverage)](https://codecov.io/github/coala-analyzer/coala?branch=master)
+[![Scrutinizer Code Quality](<https://img.shields.io/scrutinizer/g/coala-analyzer/coala.svg?label=scrutinizer quality>)](https://scrutinizer-ci.com/g/coala-analyzer/coala/?branch=master) [![codecov.io](<https://img.shields.io/codecov/c/github/coala-analyzer/coala/master.svg?label=branch coverage>)](https://codecov.io/github/coala-analyzer/coala?branch=master)
```

In that case we usually don't want the `<>`s around the links, do we?

**Comment by wooorm** [comment]
This has nothing to do with links. Rather, with spaces. In that case, [we do](https://github.com/wooorm/mdast/blob/901f3aa8e3de4bbc998e652809a795f090be7848/lib/stringify.js#L297-L301), because spaces inside URLs are not supported by all vendors. For example, [CommonMark](http://spec.commonmark.org/dingus/?text=%5B!%5BScrutinizer%20Code%20Quality%5D(https%3A%2F%2Fimg.shields.io%2Fscrutinizer%2Fg%2Fcoala-analyzer%2Fcoala.svg%3Flabel%3Dscrutinizer%20quality)%5D(https%3A%2F%2Fscrutinizer-ci.com%2Fg%2Fcoala-analyzer%2Fcoala%2F%3Fbranch%3Dmaster)).
